### PR TITLE
Update CSRF Token Implementation for API Requests

### PR DESCRIPTION
**Pull request by michaelwehrley**
* For the angular json API requests, change `protect_from_forgery` to be `with: :null_session`.
* This fixes JSON bug requests for participants.
* Add controller spec to test `protect_from_forgery with: :null_session` for json requests

[#111958897]

### CODE REVIEW

**Comment by ericcf** [comment]
@michaelwehrley can you explain more about when these requests are occurring? How does the participant experience change with this update? Thanks.

**Comment by michaelwehrley** [comment]
I am not sure exactly how to answer this question.  The experience doesn't change for a participant or user at all except that now they can complete js actions such as liking and commenting that use the rails API.

**Comment by ericcf** [comment]
Do you mean they can't like or comment currently?

**Comment by michaelwehrley** [comment]
@ericcf In this case (https://sentry.cbits.northwestern.edu/cbits/moodtech/issues/250/) my best guess is that the someone was editing the slide and waited too long to submit the form and the CSRF token expired.  I could close this pull request; however, initially I made the change because this error is becoming more popular - especially with the update of rails to 4.2.5 (i.e., in Marigold).  In that case, the same error occurs when a participant tries to like or comment or make any API request via javascript (https://www.pivotaltracker.com/projects/1392482/stories/111326814).  In Sunnyside this error is now thrown when a user gets logged out automatically after their session has expired. (https://sentry.cbits.northwestern.edu/cbits/sunnyside/issues/249/)  Please let me know your thoughts.  Thanks.

**Comment by ericcf** [comment]
What I'm getting at is: what happens when the Participant tries to like or comment and the session has expired? Will they see a message of some sort? Will it silently fail? Thanks.

**Comment by michaelwehrley** [comment]
When that happens, there is a javascript error, but nothing for the participant to see.  Are you thinking we should add a feature for displaying an alert/notification of sort?

**Comment by ericcf** [comment]
I think that would be preferable to a silent error. What do you think?

I'm also trying to understand the purpose of this particular PR: is it to eliminate exception notifications?

**Comment by michaelwehrley** [comment]
That is correct; it was designed to fix the exception reported in sentry linked to above.

**Pull request closed without merging**
