### PR TITLE
Update SocialNetworking

### PR DESCRIPTION
**Pull request by michaelwehrley**
Update SocialNetworking

* Update `social_networking` to 0.4.1

### CODE REVIEW

**Comment by ericcf** [comment]
@michaelwehrley go ahead and merge this when CI completes. No need to create PRs for version bumps!

**Comment by michaelwehrley** [comment]
@ericcf but won't it really stink if the version bump broke things? :nose:

**Comment by ericcf** [comment]
Yeah, but I can't think of any examples of what would break.

**Comment by michaelwehrley** [comment]
Are you saying that if SN already passes, how could it break once it is integrated?

**Comment by ericcf** [comment]
Yes, assuming you test it locally. All I can think of is that there might be a CI specific problem.

**Comment by michaelwehrley** [comment]
Yeah, see I am in the habit of letting travis test it - not me.  That is why I was thinking a PR was necessary.

**Pull request closed without merging**
