### PR TITLE
Change Goal Status Text

### PR DESCRIPTION
**Pull request by michaelwehrley**
Change Goal Status Text

* Change goal status text from "Created" to "Did Not Complete"

[Finishes: #92231126]

### CODE REVIEW

**Comment by cbrenner04** [comment]
@michaelwehrley should there be a test for this?

**Comment by michaelwehrley** [comment]
I think we have gone back and forth over testing something this simple.  I can add one if we think it makes sense.  Thoughts?

**Comment by ericcf** [comment]
I don't think a test is necessary. However why isn't this method in social_networking?

**Comment by michaelwehrley** [comment]
Not sure.  That was where it was.  I am trying to think why it wasn't there in the first place.

**Comment by cbrenner04** [comment]
@eschlange can you shed some lights?

**Comment by eschlange** [comment]
@michaelwehrley @cbrenner04 I added the change to the Base Goal model within the SocialNetworking app. This pull request can be closed and deleted, it is no longer necessary.

**Pull request closed without merging**
