### PR TITLE
Fix Hamburger Menu

### PR DESCRIPTION
**Pull request by michaelwehrley**
Fix Hamburger Menu

* Display Hamburger menu based on viewport not "phone request"
* Load snap file
* Snap file is activated through media query.

[#95745360]

### CODE REVIEW

**Comment by michaelwehrley** [comment]
In conjunction with https://github.com/cbitstech/think_feel_do_engine/pull/165

**Comment by cbrenner04** [comment]
@michaelwehrley I think this handles this story as well if you'd like to mark that as started and then finished, etc https://www.pivotaltracker.com/story/show/95546804

**Comment by michaelwehrley** [comment]
Thanks.  Until then, I am going to need to look and see who initially built this to help me out and make sure that this is okay.

**Comment by ericcf** [comment]
:pizza: :pizza:

**Pull request merged**
